# Generated by Django 5.1.1 on 2024-10-29 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Checkout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fullname",
                    models.CharField(max_length=200, verbose_name="Full Name"),
                ),
                ("email", models.EmailField(max_length=50, verbose_name="Email")),
                ("phone", models.IntegerField()),
                ("address", models.CharField(max_length=100, verbose_name="Address")),
                ("city", models.CharField(max_length=100, verbose_name="City")),
                ("state", models.CharField(max_length=100)),
                (
                    "payment_type",
                    models.CharField(max_length=50, verbose_name="Payment Type"),
                ),
            ],
        ),
    ]
