# Generated by Django 5.1.1 on 2024-11-01 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dressApp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="checkout",
            name="payment_type",
        ),
        migrations.AddField(
            model_name="checkout",
            name="payment_method",
            field=models.CharField(
                default=2, max_length=50, verbose_name="Payment method"
            ),
            preserve_default=False,
        ),
    ]
