# Generated by Django 5.1.1 on 2024-11-01 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dressApp", "0002_remove_checkout_payment_type_checkout_payment_method"),
    ]

    operations = [
        migrations.RenameField(
            model_name="checkout",
            old_name="fullname",
            new_name="name",
        ),
    ]
